---
- name: Run PCP commands
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Install pcp package
      apt:
        name: pcp
        state: present

    - name: Start pmcd service
      shell: invoke-rc.d pmcd start
      register: pmcd_output

    - name: Display pmcd output
      debug:
        var: pmcd_output.stdout_lines

    - name: Start pmie service
      shell: invoke-rc.d pmie start
      register: pmie_output

    - name: Display pmie output
      debug:
        var: pmie_output.stdout_lines

    - name: Start pmlogger service
      shell: invoke-rc.d pmlogger start
      register: pmlogger_output

    - name: Display pmlogger output
      debug:
        var: pmlogger_output.stdout_lines

    - name: Run pminfo command
      shell: pminfo
      register: pminfo_output

    - name: Display pminfo output
      debug:
        var: pminfo_output.stdout_lines

    - name: Run pmstat command
      shell: pmstat
      register: pmstat_output

    - name: Display pmstat output
      debug:
        var: pmstat_output.stdout_lines

    - name: Run pmrep command
      shell: pmrep -p -h surf kernel.all.load kernel.all.pswitch
      register: pmrep_output

    - name: Display pmrep output
      debug:
        var: pmrep_output.stdout_lines

    - name: Run pmval command
      shell: pmval proc.nprocs
      register: pmval_output

    - name: Display pmval output
      debug:
        var: pmval_output.stdout_lines

    - name: Run pmval command with options
      shell: pmval -h dove -t 5sec -s 4 kernel.percpu.cpu.idle
      register: pmval_options_output

    - name: Display pmval command with options output
      debug:
        var: pmval_options_output.stdout_lines

    - name: Run pmval command with additional options
      shell: pmval -t 1min -i disk1 disk.dev.read
      register: pmval_additional_options_output

    - name: Display pmval command with additional options output
      debug:
        var: pmval_additional_options_output.stdout_lines

    - name: Run pminfo command with options
      shell: pminfo -T mem.util.cached
      register: pminfo_options_output

    - name: Display pminfo command with options output
      debug:
        var: pminfo_options_output.stdout_lines
