---
- name: Install and start PCP
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Install PCP
      become: yes
      apt:
        name: pcp
        state: present

    - name: Start pmcd service
      become: yes
      service:
        name: pmcd
        state: started

    - name: Start pmie service
      become: yes
      service:
        name: pmie
        state: started

    - name: Start pmlogger service
      become: yes
      service:
        name: pmlogger
        state: started
    - name: Run pminfo command
      become: true
      command: pminfo

    - name: Run pmstat command
      become: true
      command: pmstat

    - name: Run pmrep command
      become: true
      command: pmrep -p -h surf kernel.all.load kernel.all.pswitch

    - name: Run pmval command
      become: true
      command: pmval proc.nprocs

    - name: Run pmval command with specific options
      become: true
      command: pmval -h dove -t 5sec -s 4 kernel.percpu.cpu.idle

    - name: Run pmval command with specific options
      become: true
      command: pmval -t 1min -i disk1 disk.dev.read

    - name: Run pminfo command with specific option
      become: true
      command: pminfo -T mem.util.cached
